apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target
  namespace: longhorn-system
value: "s3://k3s-longhorn@auto/longhorn/"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target-credential-secret
  namespace: longhorn-system
value: "longhorn-r2-backups"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backupstore-poll-interval
  namespace: longhorn-system
value: "300"
