apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases

resources:
  - secret-r2-creds.sops.yaml
  - secret-superuser.sops.yaml
  - keycloak-db-creds.sops.yaml
  - cluster.yaml
  - scheduled-backup.yaml
  - keycloak-database.yaml

patchesStrategicMerge:
  - patch-managed-roles.yaml