apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-bacherik-realm
  namespace: keycloak
spec:
  redirectRegex:
    regex: "^https://auth\\.bacherik\\.de/?$"
    replacement: "https://auth.bacherik.de/realms/bacherik/account"
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    traefik.ingress.kubernetes.io/router.middlewares: keycloak-redirect-to-bacherik-realm@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - keycloak.bacherik.de
        - auth.bacherik.de
      secretName: keycloak-tls
  rules:
    - host: keycloak.bacherik.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
    - host: auth.bacherik.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
