apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - namespace.yaml
  - middleware.yaml
  - route.yaml
  - secret.yaml
  - service.yaml
  - statefulSet.yaml
  - ingress.yaml
