apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth-client
type: Opaque
stringData:
    client_secret: ENC[AES256_GCM,data:br+5fbGMKPOJ67OSSgXTmR2fr+a/L1cp/vrLBonXR+Y=,iv:5G03JzRj/BdZsuER2Tlz7iiIoM9eQeOVwNWEfljiWVQ=,tag:6aVcsRnPVC+EsE1qQTW+Ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRHk0M1dHa0FxYjYvQWJD
            TmJPSHFESG5vNkhpSFFHb0pSejdzQStLaDM0Ck5uTVcxLzZMTk92aWlQUnNBVDFj
            a1c3UHptU0c4WjNOT1dVYS8rYjlZWWsKLS0tIER2YzhscjdMZFdDNS9naDhYZXV3
            aWVpSVZXaTN3bnJNYUlEcWs3dVpDVVUKRRXeeFeiZmiZGJ9TZVw1CeL+Sc1sX6+x
            8uI3K411FsKYMSjoL2mwhAwBW4AcCZbfnQaKJp0V83nf66afZ+HuZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T17:19:43Z"
    mac: ENC[AES256_GCM,data:P23tfbLiYOqUNeeCSs4n2zedZEbWIgMZziTSns/SBnO4F9yANWV1p5lG9uVPU1YZnEW/Onvc+KlO5V0JYzaCztsUdQcn3hgUiUvfEpQqUff6GFMr78W37cgA4kFPEIm/ZIgg4b+VD+izWawHSm28DQ0T4iDFihu0RoqkAgSzQzE=,iv:iKUdLjD6Dl6PVC+INXu2mwHvmXLNnhAduHce1EkS+Pw=,tag:V4gw0bv5GciE4G/vJlGhVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
