apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases

resources:
  - keycloak-role-secret.sops.yaml
  - keycloak-database.yaml

patchesStrategicMerge:
  - keycloak-role-patch.yaml