apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zitadel
resources:
  - namespace.yaml
  - secret.yaml
  - db-credentials.yaml
  - db.yaml
  - helm-repo.yaml
  - helm-release.yaml