apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/traefik
  - ../base/nginx-download
  - ../base/gethomepage
  - ../base/homepage
  - ../base/diskube
  - ../base/glance
  - ../base/haste-server
  - ../base/killedby
  - ../base/weave-gitops
  - ../base/kube-prometheus-stack
  - ../base/gatus
  #- ../base/erik-test
  - ../base/reposilite
  #- ../base/points
  - ../base/n8n
  - ../base/redirects
  - ../base/rtmp
  - ../base/live-video
  - ../base/zitadel
  #- ../base/stirlingpdf
  #- ../base/shlink
#  - ../base/open-webui
#  - ../base/weblate